package tradingbot.agent.infrastructure.persistence;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

/**
 * DeadLetterEntity — persists every event that was routed to a Kafka DLT (.DLT topic).
 *
 * Provides an audit trail of processing failures so:
 *  - Ops can query / replay / discard specific failures
 *  - Alert logic can count failures per topic over a sliding window
 *  - Post-mortem analysis can be performed without relying on Kafka retention
 */
@Entity
@Table(name = "dead_letter_events", indexes = {
    @Index(name = "idx_dle_topic",        columnList = "original_topic"),
    @Index(name = "idx_dle_received_at",  columnList = "received_at"),
    @Index(name = "idx_dle_resolved",     columnList = "resolved"),
    @Index(name = "idx_dle_exception",    columnList = "exception_type")
})
public class DeadLetterEntity {

    @Id
    private String id;  // UUID generated by the consumer

    /** The original topic that failed (without the .DLT suffix). */
    @Column(name = "original_topic", nullable = false)
    private String originalTopic;

    @Column(name = "kafka_partition", nullable = false)
    private int partition;

    @Column(name = "kafka_offset", nullable = false)
    private long kafkaOffset;

    /** The message key (symbol, agentId, etc.) — may be null for unkeyed messages. */
    @Column(name = "message_key")
    private String messageKey;

    /** Raw serialised value of the failed message (truncated to 4 000 chars). */
    @Column(name = "message_value", length = 4000)
    private String messageValue;

    /** Simple class name of the exception that caused the failure. */
    @Column(name = "exception_type", nullable = false, length = 255)
    private String exceptionType;

    /** Exception message (truncated to 1 000 chars). */
    @Column(name = "exception_message", length = 1000)
    private String exceptionMessage;

    /** First 2 000 characters of the stack trace for triage. */
    @Column(name = "stack_trace", length = 2000)
    private String stackTrace;

    /** Timestamp when the DLT consumer received the event. */
    @Column(name = "received_at", nullable = false)
    private Instant receivedAt;

    /**
     * Whether an operator has acknowledged/resolved this failure.
     * Default false — ops must explicitly mark resolved after replay or discard.
     */
    @Column(nullable = false)
    private boolean resolved = false;

    /** Timestamp when the failure was resolved; null until resolved = true. */
    @Column(name = "resolved_at")
    private Instant resolvedAt;

    /** Optional free-text note added when resolving (e.g. "replayed manually"). */
    @Column(name = "resolution_note", length = 500)
    private String resolutionNote;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public DeadLetterEntity() {}

    public DeadLetterEntity(String id, String originalTopic, int partition, long kafkaOffset,
                             String messageKey, String messageValue,
                             String exceptionType, String exceptionMessage, String stackTrace,
                             Instant receivedAt) {
        this.id = id;
        this.originalTopic = originalTopic;
        this.partition = partition;
        this.kafkaOffset = kafkaOffset;
        this.messageKey = messageKey;
        this.messageValue = messageValue;
        this.exceptionType = exceptionType;
        this.exceptionMessage = exceptionMessage;
        this.stackTrace = stackTrace;
        this.receivedAt = receivedAt;
        this.resolved = false;
    }

    // -------------------------------------------------------------------------
    // Getters / Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getOriginalTopic() { return originalTopic; }
    public void setOriginalTopic(String originalTopic) { this.originalTopic = originalTopic; }

    public int getPartition() { return partition; }
    public void setPartition(int partition) { this.partition = partition; }

    public long getKafkaOffset() { return kafkaOffset; }
    public void setKafkaOffset(long kafkaOffset) { this.kafkaOffset = kafkaOffset; }

    public String getMessageKey() { return messageKey; }
    public void setMessageKey(String messageKey) { this.messageKey = messageKey; }

    public String getMessageValue() { return messageValue; }
    public void setMessageValue(String messageValue) { this.messageValue = messageValue; }

    public String getExceptionType() { return exceptionType; }
    public void setExceptionType(String exceptionType) { this.exceptionType = exceptionType; }

    public String getExceptionMessage() { return exceptionMessage; }
    public void setExceptionMessage(String exceptionMessage) { this.exceptionMessage = exceptionMessage; }

    public String getStackTrace() { return stackTrace; }
    public void setStackTrace(String stackTrace) { this.stackTrace = stackTrace; }

    public Instant getReceivedAt() { return receivedAt; }
    public void setReceivedAt(Instant receivedAt) { this.receivedAt = receivedAt; }

    public boolean isResolved() { return resolved; }
    public void setResolved(boolean resolved) { this.resolved = resolved; }

    public Instant getResolvedAt() { return resolvedAt; }
    public void setResolvedAt(Instant resolvedAt) { this.resolvedAt = resolvedAt; }

    public String getResolutionNote() { return resolutionNote; }
    public void setResolutionNote(String resolutionNote) { this.resolutionNote = resolutionNote; }
}
